var brick;
var gltfLoader;
var brickClone;
var scene;
var group1 = new Array();
var geometryMaterial1;
var brickContainer ;
var ground;
var landscape;
var wallGeometry;
var geometryMaterial;
var brickLoaded;
var groupContainer;
var geometryMaterial2;
var groupContainerTop;
var brickGeometry;
var torch;
var torchClone;
var torchLoaded;
var torch2;
var torchClone2;
var torchLoaded2;
var box;
var boxClone;
var boxLoaded;
var spear;
var spearLoaded;
var spearClone;
